version: "3.7"

networks:
  proxy:
    external: true
  draw-internal:
    name: draw-internal
    external: false

volumes:
  excalidraw_db:
    driver: local

services:
  app:
    image: alswl/excalidraw:v0.17.3-fork-b1
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=https://${STORAGE_BACKEND_HOST}/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=https://${ROOM_HOST}/
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=https://${STORAGE_BACKEND_HOST}/api/v2
      - VITE_APP_STORAGE_BACKEND=http
      - VITE_APP_DISABLE_TRACKING=true
      - PUBLIC_URL=https://${APP_HOST}
    networks:
      - ${TRAEFIK_NETWORK_NAME}
    healthcheck:
      disable: true
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-app.entrypoints=${TRAEFIK_ENTRYPOINT}"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-app.rule=Host(`${APP_HOST}`)"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-app.service=${TRAEFIK_LABEL_ID}-app"
        - "traefik.http.services.${TRAEFIK_LABEL_ID}-app.loadbalancer.server.port=80"

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: unless-stopped
    environment:
      - STORAGE_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
    networks:
      - ${TRAEFIK_NETWORK_NAME}
      - draw-internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-storage.entrypoints=${TRAEFIK_ENTRYPOINT}"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-storage.rule=Host(`${STORAGE_BACKEND_HOST}`)"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-storage.service=${TRAEFIK_LABEL_ID}-storage"
        - "traefik.http.services.${TRAEFIK_LABEL_ID}-storage.loadbalancer.server.port=8080"

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    restart: unless-stopped
    networks:
      - ${TRAEFIK_NETWORK_NAME}      
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-room.entrypoints=${TRAEFIK_ENTRYPOINT}"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-room.rule=Host(`${ROOM_HOST}`)"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-room.service=${TRAEFIK_LABEL_ID}-room"
        - "traefik.http.services.${TRAEFIK_LABEL_ID}-room.loadbalancer.server.port=80"

  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - excalidraw_db:/data/db
    networks:
      - draw-internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=false"

  mongoexpress:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASS}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - ${TRAEFIK_NETWORK_NAME}
      - draw-internal
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-db.entrypoints=${TRAEFIK_ENTRYPOINT}"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-db.rule=Host(`${MONGOEXPRESS_HOST}`)"
        - "traefik.http.routers.${TRAEFIK_LABEL_ID}-db.service=${TRAEFIK_LABEL_ID}-db"
        - "traefik.http.services.${TRAEFIK_LABEL_ID}-db.loadbalancer.server.port=8081"
